INSERT INTO health_problems (name, active, degree)
VALUES
  ('CANCER', true, NULL),
  ('DIABETES', true, 1),
  ('DIABETES', true, 2),
  ('HEART DISEASE', true, NULL),
  ('HYPERTENSION', true, NULL),
  ('ARTHRITIS', true, NULL),
  ('ASTHMA', true, NULL),
  ('OBESITY', true, NULL),
  ('STROKE', true, NULL),
  ('ALZHEIMER''S', true, NULL),
  ('DEPRESSION', true, NULL),
  ('ANXIETY', true, NULL),
  ('HIV/AIDS', true, NULL),
  ('PARKINSON''S', true, NULL),
  ('CHRONIC OBSTRUCTIVE PULMONARY DISEASE (COPD)', true, NULL),
  ('OSTEOPOROSIS', true, NULL),
  ('EPILEPSY', true, NULL),
  ('AUTISM', true, NULL),
  ('MULTIPLE SCLEROSIS', true, NULL),
  ('SCHIZOPHRENIA', true, NULL),
  ('INFLUENZA', true, NULL);